before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - export DIR=$(date +%Y%m%d_%H%M%S)

deploy_server1:
  stage: deploy
  environment:
    name: server1
    url: $SERVER1
  script:
    - ssh $SSH_USER@$SERVER1 "cd /var/www/demo &&
      git clone https://github.com/otusteamedu/symfony-deploy-2024-11.git $DIR &&
      sudo chown www-data:www-data $DIR -R &&
      cd $DIR &&
      sh ./deploy.sh $SERVER1 $DATABASE_HOST $DATABASE_USER $DATABASE_PASSWORD $DATABASE_NAME $RABBITMQ_HOST $RABBITMQ_USER $RABBITMQ_PASSWORD &&
      cd .. &&
      rm -rf /var/www/demo/$DIR/var/log &&
      ln -s /var/www/demo/shared/log /var/www/demo/$DIR/var/log &&
      ( [ ! -d /var/www/demo/current ] || mv -Tf /var/www/demo/current /var/www/demo/previous ) &&
      ln -s /var/www/demo/$DIR /var/www/demo/current"
  only:
    - main
